-- The local-first schema — same shape as schema.postgres.sql, in SQLite
-- dialect, so the eventual Supabase migration is a straight data copy.
-- Applied automatically by lib/store.py on first open. UUIDs are generated by
-- the caller (Python uuid4); timestamps are ISO-8601 TEXT in UTC.

create table if not exists expense_tracker_bank_connections (
  id text primary key,
  bank text not null,               -- 'lloyds' or 'hsbc'
  access_token text not null,
  refresh_token text,
  consent_expires_at text not null,
  last_pulled_at text,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

create table if not exists expense_tracker_transactions (
  id text primary key,
  bank text not null,
  account_id text not null,
  source_transaction_id text not null unique,
  date text not null,
  amount numeric not null,
  currency text not null default 'GBP',
  raw_description text not null,
  category text,
  reviewed integer not null default 0,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

-- Dedupe contract: the UNIQUE on source_transaction_id plus INSERT OR IGNORE
-- is the whole mechanism. Skipped, never upserted — category and reviewed may
-- carry manual edits a pull must never overwrite.
